name: e_shop
description: Flutter eCommerce App using Firebase Firestore from Kood

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  flutter_launcher_icons: ^0.8.0
  flutter_launcher_name: ^0.0.1
  cupertino_icons: ^1.0.0
  cloud_firestore: ^0.14.1+3
  firebase_auth: ^0.18.1+2
  shared_preferences: ^0.5.6+1
  fluttertoast: ^7.1.1
  image_picker: ^0.6.3+1
  firebase_storage: ^4.0.1
  flutter_staggered_grid_view: ^0.3.0
  provider: ^4.0.4
  path_provider: ^1.6.18
  image: ^2.0.7
  intl:


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_name:
  name: "Buyt"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.png"

flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf

  assets:
    - images/welcome.png
    - images/login.png
    - images/admin.png
    - images/cash.png




